### PR TITLE
Update GHA flow, return package.json

### LINKED ISSUE #6: Build not working
https://github.com/expresslang/ap210.org/actions/runs/1650405177

### PR DESCRIPTION
**Pull request by ronaldtse**
Attempt to fix #6 .

### CODE REVIEW

**Comment by TRThurman** [comment]
Is this error branch dependent?
I note I see 
main,
master,
develop.

Which should we be committing and pushing to?
thanks,
Tom

**Comment by ronaldtse** [comment]
We technically only should work with `main`. `master` is the deprecated branch. @strogonoff is handling this one now.

**Comment by strogonoff** [comment]
We are using `main` with this project. Default branch name is configurable in Paneron, so given repository can use any default branch name (but it’s tough to change after the fact without disrupting work).

**Comment by TRThurman** [comment]
Thanks!

Sent from my iPhone

**Pull request merged**
